trigger:
- main

resources:
- repo: self

stages:
- stage: Verify
  displayName: Verify code
  jobs:
    - job: SonarQube
      displayName: SonarQube
      steps:
        - task: SonarQubePrepare@5
          inputs:
            SonarQube: 'SonarQube-Eindhoven'
            scannerMode: 'CLI'
            configMode: 'file' 
        - task: SonarQubeAnalyze@5
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        - task: SonarQubePublish@5
          inputs:
            pollingTimeoutSec: '300'
